### ISSUE TITLE
Service port

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqcwebapi#15]
@frank-24 @394822740 Some questions:
- Is 5000 the default port for MRIQCWebAPI?
- How can I change the port where the endpoints are open?
- Is there a dynamic way to do it (meaning, without changing [the docker-compose.yml file](https://github.com/poldracklab/mriqcwebapi/blob/master/dockereve-master/docker-compose.yml#L17))

**Comment by chrisgorgo** [comment]
- Technically this was designed to work on port 80. nginx acts as a proxy redirecting all traffic to gnuicorn at port 5000
- To change nginx and/or gnuincorn ports you would have to edit https://github.com/poldracklab/mriqcwebapi.git and https://github.com/poldracklab/mriqcwebapi/blob/master/dockereve-master/docker-compose.yml
- It's not configured to be done dynamically at the moment - why would you need this to be done dynamically?

**Comment by oesteban** [comment]
- 80 is a protected port, I think you can't use it even in localhost unless you set up the firewall to do so. I'm not 100% sure but first time I tried, it was on port 80 and the connection couldn't be done.
- I also have the impression that parallel builds are colliding in CircleCI, hence the need to change the ports.
