### ISSUE TITLE
JSON schemas

### ISSUE THREAD

**Issue by oesteban** [nipreps/mriqcwebapi#18]
Right now, we flatten the dictionary in the client side, making it impossible for the server to know if a field is an IQM or if it is under an special key (`'metadata'`, `'settings'` and `'warnings'`).

This is a limiting factor for both the client and the server, because it adds an unnecessary complexity into the client (e.g. [this rather unreliable dictionary](https://github.com/oesteban/mriqc/blob/426176151562d5f7ebf0e43f8b06f2e9e212ee72/mriqc/interfaces/webapi.py#L21)). But also limits the server: we designed the `settings/software` field so that, at some point, tools other than mriqc would upload their own IQMs. Right now, all the accepted keywords are hard-coded in both client and server: so only mriqc IQMs would be valid. Right now, it is a bit painful to add new IQMs: it requires a big deal of cohesion between mriqcwebapi and mriqc. And cohesion is generally a bad idea (I can see similar tensions and problems to those we have with niworkflows and nipype, trying to keep versions consistent).

The client should take care of not sending identifiable personal information. So it makes sense to hard-code a dictionary of BIDS metadata keys that can be copied to the JSON derivatives. That could be done with the list linked before, but restricted to only BIDS keys (so no md5sum in that list, for instance).

The server should take care of all the rest: split IQMs vs. metadata (and settings), validate the field, and double check no personal info is inserted. If the dictionary comes flattened, this is a lot harder.

Does it make sense?

**Comment by vsoch** [comment]
I'm not sure about the details of your metadata, but if you are making a json API --> [schema!](http://jsonapi.org/)

**Comment by oesteban** [comment]
This is not an issue anymore since #21 was merged.
