### ISSUE TITLE
HTTPS encryption of connection from proxy server to mriqcep server

### ISSUE THREAD

**Issue by Shotgunosine** [nipreps/mriqcwebapi#28]
We should be encrypting all of the traffic for mriqc, but currently the proxy server points to http://34.224.227.208. We need to enable https connection on the mriqc end point server so that the proxy server can point to https://34.224.227.208.

**Comment by oesteban** [comment]
The server is now deployed here: https://mriqc.nimh.nih.gov/ and the API endpoints are now under https://mriqc.nimh.nih.gov/api/v1/. Python's `requests` handles encryption automatically.

Maybe you were suggesting something I did not get. In that case, feel free to point that out and reopen this issue.

Thanks!

**Comment by chrisgorgo** [comment]
Apologies @Shotgunosine - you are correct in your assessment. This is still an issue.

**Comment by oesteban** [comment]
Sorry @Shotgunosine :+1:

**Comment by Shotgunosine** [comment]
No worries. If you can get a signed cert for http://34.224.227.208 I can help get nginx configured to use https.

**Comment by chrisgorgo** [comment]
According to @rwblair you cannot get certificates for IP addresses (they have to be names)

**Comment by rwblair** [comment]
Looks like it may be possible but not with LetsEncrypt:
https://stackoverflow.com/questions/2043617/is-it-possible-to-have-ssl-certificate-for-ip-address-not-domain-name


On Jun 5, 2017 10:40 AM, "Chris Filo Gorgolewski" <notifications@github.com>
wrote:

According to @rwblair <https://github.com/rwblair> you cannot get
certificates for IP addresses (they have to be names)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/poldracklab/mriqcwebapi/issues/28#issuecomment-306254032>,
or mute the thread

**Comment by Shotgunosine** [comment]
Since this is just for communication between two trusted hosts, I think it's fine if we use a self signed cert. I've created a keypair at /home/ubuntu/ssl.

**Comment by Shotgunosine** [comment]
Should be able to get https working by adding something like the following to then nginx config:

```
server {
    listen 80;
    listen [::]:80 ;
    server_name 34.224.227.208;

    # Redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name 34.224.227.208;

    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
    ssl_password_file /etc/ssl/.mriqcep_pass;
    ssl_certificate /etc/ssl/certs/mriqcep-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/mriqcep-selfsigned.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;


    # modern configuration. tweak to your needs.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "ECDH+AESGCM:ECDH+AES256:ECDH+AES128:ECDH+3DES:RSA+AES:RSA+3DES:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!ADH:!AECDH:!MD5:!DSS:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA";
    ssl_prefer_server_ciphers on;

    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;

    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;

    ## verify chain of trust of OCSP response using Root CA and Intermediate certs
    #ssl_trusted_certificate /etc/ssl/certs/ssl_trusted_cert.crt;

    #resolver <IP DNS resolver>;
    resolver_timeout 5s;

    charset     utf-8;

    # max upload size
    client_max_body_size 75M;   # adjust to taste

    location / {
      proxy_pass http://34.224.227.208;
    }
}
```


And the following to the dockerfile:

```
# Copy certs in
COPY /home/ubuntu/ssl/mriqcep-selfsigned.crt /etc/ssl/certs/mriqcep-selfsigned.crt
COPY /home/ubuntu/ssl/mriqcep-selfsigned.key /etc/ssl/private/sslkey.key
COPY /home/ubuntu/ssl/mriqcep_pass /etc/ssl/mriqcep_pass
```

**Comment by rwblair** [comment]
Thank you Dylan, I updated the nginx and docker configuration and the site
is now serving a self signed cert from https://34.224.227.208.

**Comment by Shotgunosine** [comment]
Fantastic, thanks @rwblair. I've updated the proxy server to point to https://34.224.227.208. This is resolved.
