### ISSUE TITLE
Add test for querying all images in the database

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqcwebapi#4]
Current tests check POST and GET for individual images. We should also test doing GET at the main endpoint that should return all images.

**Comment by frank-24** [comment]
Should we put this part in a new test case?

**Comment by chrisgorgo** [comment]
Yes that would ideally be a new test (using the same data), and a new PR.

**Comment by frank-24** [comment]
Hi Chris, It would be really helpful if you could show me the source code of `GET` & `POST`. I don't quite understand what `GET` and `POST` will do in this API.

For querying all images:  
with `GET`, I can only get 25 results while I `POST` 84 `json` files. 
In the `localhost/scenarios` page, under `meta` tag, it shows:  
```xml
<_meta>
  <max_results>25</max_results>
```

**Comment by chrisgorgo** [comment]
I thing your code snippet got truncated.

The reason you get only 25 results is probably because pagination is turned on (which is good). See http://python-eve.org/features.html#pagination

**Comment by frank-24** [comment]
Hi Chris, I'm confused about `querying all images in database`
1. how to do that? 
2. how & what to test?

For the first question:
As I may run the test several times, so the database would contain duplicate `json` files -- testing data. Should we return all the files, or return unique files?

**Comment by frank-24** [comment]
3. I think I'm confused because I don't quite understand what `POST` & `GET` would actually do in this API. Would you have any suggestions such as source code in this API?

**Comment by chrisgorgo** [comment]
1. A GET on the main API endpoint (without [specifying entity ID](https://github.com/poldracklab/mriqcwebapi/blob/master/test/testGetPost.py#L11) as you are doing in other tests) should give you paginated list of all entities.
2. One good test would be to check if the expected total number of items is correct (see "total" inside "_meta" of returned response)
3. Its here: https://github.com/poldracklab/mriqcwebapi/tree/master/dockereve-master Have you talked with @394822740?

Deduplication would be desirable (checking 'md5sum' and 'version' should be enought), but that would be a separate feature. Otherwise it would be nice to wipe the database (or use a test database) between tests. Mongo does that for their testing). However, you should not run into this issue with Circle since each time you spin a new database.

**Comment by frank-24** [comment]
Great, thanks! 
I'll read the documentation and work on this.

3. Yeah. And I'll read the document
