### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by dkp** [nipreps/mriqcwebapi#52]
@rwblair Is the mriqc server down?  
We are getting complaints that data cannot be uploaded or retrieved.

**Comment by rwblair** [comment]
Looks like there are connection issues to the database. Trying to figure out whats going on, will let you know when its back up.

**Comment by rwblair** [comment]
@dkp Sorry for the delay and downtime. Should be online again, let me know if you run into any issues.

**Comment by dkp** [comment]
Thanks so much!
