### ISSUE TITLE
Changes to the API fields

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqcwebapi#8]
After some deliberation we had to limit the metadata fields that will be sent to this API. This was motivated by the fact that we should avoid a situation when a misused metadata field would accidentally include personal health information (see https://github.com/poldracklab/mriqc/pull/464#issuecomment-297178070).

The following are the only allowed metadata fields.
- ContrastBolusIngredient
- RepetitionTime
- TaskName
- Manufacturer
- ManufacturersModelName
- MagneticFieldStrength
- DeviceSerialNumber
- SoftwareVersions
- HardcopyDeviceSoftwareVersion
- ReceiveCoilName
- GradientSetType
- MRTransmitCoilSequence
- MatrixCoilMode
- CoilCombinationMethod
- PulseSequenceType
- PulseSequenceDetails
- NumberShots
- ParallelReductionFactorInPlane
- ParallelAcquisitionTechnique
- PartialFourier
- PartialFourierDirection
- PhaseEncodingDirection
- EffectiveEchoSpacing
- TotalReadoutTime
- EchoTime
- InversionTime
- SliceTiming
- SliceEncodingDirection
- NumberOfVolumesDiscardedByScanner
- NumberOfVolumesDiscardedByUser
- DelayTime
- FlipAngle
- MultibandAccelerationFactor
- Instructions
- TaskDescription
- CogAtlasID
- CogPOID
- InstitutionName
- InstitutionAddress
- ConversionSoftware
- ConversionSoftwareVersion
- md5sum
- modality
- mriqc_pred
- software
- subject_id
- version

Please adjust the https://github.com/poldracklab/mriqcwebapi/blob/master/dockereve-master/eve-app/settings.py file.

**Comment by 394822740** [comment]
I assume these data are optional when researchers upload their data?

**Comment by chrisgorgo** [comment]
All apart from:

- md5sum
- modality
- mriqc_pred
- software
- subject_id
- version

are optional.

**Comment by 394822740** [comment]
pushed for review
