### ISSUE TITLE
Support for functional (BOLD) files

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/mriqcwebapi#9]
Currently MRIQC Web API only supports structural (T1w) files. MRIQC also calculates quality of functional (BOLD) files. Here is an example payload of such file:

```
{
aor: 0.034428499999999994,
aqi: 0.0005224403999999999,
dvars_nstd: 10.191722418947368,
dvars_std: 1.0800233642105264,
dvars_vstd: 1.6403423489473683,
efc: 0.5638485423014671,
fber: 958.6884765625,
fd_mean: 0.16413075091049215,
fd_num: 4,
fd_perc: 20,
fwhm_avg: 40.5562,
fwhm_x: 37.569,
fwhm_y: 43.0101,
fwhm_z: 41.283,
gcor: 0.2162099838256836,
gsr_x: -0.004743137396872044,
gsr_y: 0.02154964953660965,
RepetitionTime: 2,
TaskName: "rhyme judgment",
md5sum: "bae64aa6144d8f5d19e56d4c28ff2bda",
modality: "bold",
software: "mriqc",
subject_id: "ds003s01",
task_id: "rhymejudgment",
version: "99.99.99",
size_t: 20,
size_x: 16,
size_y: 16,
size_z: 9,
snr: 1.1260140530360272,
spacing_tr: 2,
spacing_x: 12.5,
spacing_y: 12.5,
spacing_z: 16,
summary_bg_k: 10.199746320897564,
summary_bg_mean: 10.67599868774414,
summary_bg_p05: 3.4488043785095215,
summary_bg_p95: 21.972539520263666,
summary_bg_stdv: 5.769111156463623,
summary_fg_k: -1.6145134278870812,
summary_fg_mean: 290.6355895996094,
summary_fg_p05: 13.376275062561035,
summary_fg_p95: 631.4849853515625,
summary_fg_stdv: 238.1324462890625,
tsnr: 108.249267578125
}
```

As you can see it includes different, but overlapping set of measures. To support this data type the API schema needs to be adjusted.

**Comment by 394822740** [comment]
Are all the above data field required or optional when researchers upload their data?

**Comment by chrisgorgo** [comment]
if `modality == "bold"` all of those fields with exception of `RepetitionTime` and `TaskName` are compulsory.

**Comment by 394822740** [comment]
pushed for review

**Comment by vsoch** [comment]
Woohoo @394822740 ! Welcome to Poldracklab! I'm really glad you guys connected :O)

**Comment by vsoch** [comment]
and your beat boxing is pretty amazing, by the way!! You have fans in research computing :)

**Comment by oesteban** [comment]
@chrisfilo have we flattened the JSON files?

The `metadata` field is not there anymore?

**Comment by 394822740** [comment]
@vsoch  Thank You! Look forward to working on this together!

**Comment by chrisgorgo** [comment]
@oesteban Yes - see https://github.com/poldracklab/mriqc/pull/464#issuecomment-297178070
